### ISSUE TITLE
Data documentation: raw data

### ISSUE THREAD

**Issue by vincent-octo** [FINNGEN/kanta_lab_preprocessing#1]
| Column name in raw data       | Data type         | Comment                                                                                                                      |
|---------------------------------|---------------------|---------------------------------------------------------------------------------------------------------------------------------|
| `laboratoriotutkimusnimikeid`     | Integer             |                                                                                                                                 |
| `asiakirjaoid`                    | Opaque string       |                                                                                                                                 |
| `merkintaoid`                     | Opaque string       |                                                                                                                                 |
| `entryoid`                        | Opaque string       |                                                                                                                                 |
| `potilashenkilotunnus`            | Opaque string       | Our "FINNGENID", can use e.g. "FAKE0001", "FAKE0002"                                                                            |
| `palvelutapahtumatunnus`          | Opaque string       |                                                                                                                                 |
| `tutkimuksennaytelaatupk`         | String, categorical |                                                                                                                                 |
| `tutkimuksentekotapa`             | Integer             | not sure about this one                                                                                                         |
| `potilassyntymaaika_pvm`          | Integer             | date of birth, for example for someone born on 2025-01-01 it is "20250101"                                                      |
| `potilas_sukupuoli`               | Integer             |                                                                                                                                 |
| `laboratoriotutkimusoid`          | Opaque string       |                                                                                                                                 |
| `tutkimusaika`                    | Datetime            | format: "YYYY-MM-DD HH:MM:SS"                                                                                                   |
| `alkuperainenasiakirjaoid`        | Opaque string       |                                                                                                                                 |
| `asiakirjaversio`                 | Integer             |                                                                                                                                 |
| `rekisterinpitaja_organisaatio_h` | Opaque string       |                                                                                                                                 |
| `rekisterinpitaja_h`              | Opaque string       |                                                                                                                                 |
| `asiakirjavalmistilapk`           | Integer             |                                                                                                                                 |
| `maarittelykokoelmaoid`           | Opaque string       |                                                                                                                                 |
| `tietojarjestelmanimi`            | String, categorical |                                                                                                                                 |
| `tietojarjestelmavalmistaja`      | String, categorical |                                                                                                                                 |
| `tietojarjestelmaversio`          | Opaque string       |                                                                                                                                 |
| `asiakirjaluontiaika`             | Datetime            | format: "YYYY-MM-DD HH:MM:SS"                                                                                                   |
| `pal_alkuperainenasiakirjaoid`    | Opaque string       |                                                                                                                                 |
| `pal_asiakirjaversio`             | Integer             |                                                                                                                                 |
| `pal_asiakirjaoid`                | Opaque string       |                                                                                                                                 |
| `pal_asiakirjaluontiaika`         | Datetime            | format: "YYYY-MM-DD HH:MM:SS"                                                                                                   |
| `rekisterinpitaja_organisaatio`   | Opaque string       |                                                                                                                                 |
| `rekisterinpitaja`                | Opaque string       |                                                                                                                                 |
| `palverluntuottaja_organisaatio`  | Opaque string       |                                                                                                                                 |
| `palveluisanta_organisaatio`      | Opaque string       |                                                                                                                                 |
| `hetu_root`                       | Opaque string       |                                                                                                                                 |
| `paikallinentutkimusnimike`       | String, categorical |                                                                                                                                 |
| `paikallinentutkimusnimikeid`     | Integer             |                                                                                                                                 |
| `tutkimuskoodistonjarjestelmaid`  | Opaque string       |                                                                                                                                 |
| `tutkimusvastauksentila`          | String, categorical |                                                                                                                                 |
| `tutkimustulosarvo`               | it depends          | lab test value, sometimes a quantitative float, sometimes an integer (e.g. for titre), sometimes binary (pos / neg test result) |
| `tutkimustulosyksikkö`            | String, categorical |                                                                                                                                 |
| `tuloksenpoikkeavuus`             | String, categorical |                                                                                                                                 |
| `tuloksenvalmistumisaika`         | Datetime            | format: "YYYY-MM-DD HH:MM:SS"                                                                                                   |
| `viitearvoryhma`                  | String              |                                                                                                                                 |
| `viitevalialkuarvo`               | Float, mostly       |                                                                                                                                 |
| `viitevalialkuyksikko`            | String, categorical |                                                                                                                                 |
| `viitevaliloppuarvo`              | Float, mostly       |                                                                                                                                 |
| `viitevaliloppuyksikko`           | String, categorical |                                                                                                                                 |
| `viitevaliteksti`                 | String              |                                                                                                                                 |
| `erikoisalalyhenne`               | String              |                                                                                                                                 |

**Comment by vincent-octo** [comment]
@piotor87 Here is a file with fake data that I made based on table description above.
[kanta_lab_fake_raw_data__2024-03-28.txt](https://github.com/FINNGEN/kanta_lab_preprocessing/files/14786153/kanta_lab_fake_raw_data__2024-03-28.txt)

**Comment by vincent-octo** [comment]
Above file has some wrong column names.

Fixed in this file:
[kanta_lab_fake_raw_data__2024-03-28.1.txt](https://github.com/FINNGEN/kanta_lab_preprocessing/files/14786823/kanta_lab_fake_raw_data__2024-03-28.1.txt)

**Comment by piotor87** [comment]
We now have mock data so we can close this one.
Thanks, it was very useful in the meantime :)
